// Generated by `mcp__supabase__generate_typescript_types` against the
// pen-and-paper-two project. Regenerate after every schema change:
//
//   mcp__supabase__generate_typescript_types(project_id="gmmwypnlqjqcezwxzbiw")
//
// Do not hand-edit. Commit changes to this file alongside the migration
// that produced them.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      pens: {
        Row: {
          affinity_scores: Json | null
          archive_number: number
          body: Json
          brand: string
          city_of_origin: string | null
          country_of_origin: string
          created_at: string | null
          dimensions: Json
          edition: Json | null
          editorial: Json
          ergonomics: Json | null
          generation: string | null
          heritage: Json | null
          id: string
          in_production: boolean
          ink_delivery: Json
          model: string
          nib: Json
          performance: Json
          photos: Json
          pricing: Json
          recommended_paper_ids: string[] | null
          service: Json | null
          updated_at: string | null
          variant: string | null
          year_discontinued: number | null
          year_introduced: number
        }
        Insert: {
          affinity_scores?: Json | null
          archive_number: number
          body: Json
          brand: string
          city_of_origin?: string | null
          country_of_origin: string
          created_at?: string | null
          dimensions: Json
          edition?: Json | null
          editorial: Json
          ergonomics?: Json | null
          generation?: string | null
          heritage?: Json | null
          id: string
          in_production?: boolean
          ink_delivery: Json
          model: string
          nib: Json
          performance: Json
          photos: Json
          pricing: Json
          recommended_paper_ids?: string[] | null
          service?: Json | null
          updated_at?: string | null
          variant?: string | null
          year_discontinued?: number | null
          year_introduced: number
        }
        Update: {
          affinity_scores?: Json | null
          archive_number?: number
          body?: Json
          brand?: string
          city_of_origin?: string | null
          country_of_origin?: string
          created_at?: string | null
          dimensions?: Json
          edition?: Json | null
          editorial?: Json
          ergonomics?: Json | null
          generation?: string | null
          heritage?: Json | null
          id?: string
          in_production?: boolean
          ink_delivery?: Json
          model?: string
          nib?: Json
          performance?: Json
          photos?: Json
          pricing?: Json
          recommended_paper_ids?: string[] | null
          service?: Json | null
          updated_at?: string | null
          variant?: string | null
          year_discontinued?: number | null
          year_introduced: number
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never
